sonar.projectKey=ocpp-csms-service
sonar.projectName=OCPP CSMS Service
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
sonar.host.url=http://3.17.106.40
# sonar.login=<your-token>   # Uncomment and set if authentication is required

